# Schema for configuration files of the PHP FFMpeg module.

php_ffmpeg.settings:
  type: config_object
  label: 'PHP FFMpeg settings'
  mapping:
    ffmpeg_binary:
      type: string
      label: 'Path to the ffmpeg binary.'
    ffprobe_binary:
      type: string
      label: 'Path to the ffprobe binary.'
    execution_timeout:
      type: integer
      label: 'Timeout for ffmpeg/ffprobe command execution in seconds. Leave empty for none.'
    threads_amount:
      type: integer
      label: 'Number of threads to use for ffmpeg commands.'
